version: 2

project_name: todoist

builds:
  - skip: true

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-checksums.txt"

release:
  prerelease: auto

announce:
  skip: "{{ gt .Patch 0 }}"
  mastodon:
    enabled: false
    server: "https://social.linodians.com"
